tournament/footBallApp/urls.py
from django.conf.urls import url
from footBallApp import views
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

# SET THE NAMESPACE!
app_name = 'footBallApp'
# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    path('register/', views.register, name='register'),
    path('user_login/', views.user_login, name='user_login'),
    path('addTeam/', views.addTeam, name='addTeam'),
    path('addTeamMember/', views.addTeamMember, name='addTeamMember'),   
    path('matchScheduling/', views.matchScheduling, name='matchScheduling'),   
]

tournament/tournament/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from footBallApp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('prodMap/', include('footBallApp.urls')),
    path('', views.index, name='index'),
    path('special/', views.special, name='special'),
    path('logout/', views.user_logout, name='logout'),
]

tournament/footBallApp/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfileInfo(models.Model):
    """
    Additional informations aparts from the default user model
    """
    USER_TYPE_CHOICES = (
      (1, 'admin'),
      (4, 'manager'),
  )
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    name = models.CharField(max_length = 200)
    age = models.IntegerField(blank=True, null=True)
    user_type = models.PositiveSmallIntegerField(choices=USER_TYPE_CHOICES, default=1)
    def __str__(self):
        return self.user.username

class Teams(models.Model):
    """
    Model for creating a team
    """
    team_name = models.CharField(max_length = 200, unique=True)
    coach = models.CharField(max_length = 200)
    manager = models.CharField(max_length = 200)
    def __str__(self):
        return self.team_name

class TeamMembers(models.Model):
    """
    Model for creating a team member
    """
    team = models.ForeignKey(Teams,related_name="team",on_delete=models.CASCADE)
    name = models.CharField(max_length = 200)
    age = models.IntegerField(blank=True, null=True)
    position = models.CharField(max_length = 200)
    def __str__(self):
        return self.name

class MatchScheduling(models.Model):
    """
    Time Scheduling of the team battles
    """
    MATCH_STATUS = (
      (1, 'upcoming'),
      (2, 'inprogress'),
      (3, 'completed'),
  )
    first_team = models.ForeignKey(Teams,related_name="team1",on_delete=models.CASCADE)
    second_team = models.ForeignKey(Teams,related_name="team2",on_delete=models.CASCADE)
    start_time = models.DateTimeField(auto_now_add=True)
    end_time = models.DateTimeField(auto_now_add=True)
    match_status = models.PositiveSmallIntegerField(choices=MATCH_STATUS, default=1)
    result = models.CharField(max_length = 200, null=True, blank=True)
    def __str__(self):
        return self.first_team.team_name+" Vs "+self.second_team.team_name

tournament/footBallApp/forms.py
from django import forms
from footBallApp.models import UserProfileInfo, Teams, TeamMembers, MatchScheduling
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
	"""
	Form design for storing authentication informations to default user model
	"""
	password = forms.CharField(widget=forms.PasswordInput())
	class Meta():
		model = User
		fields = ('username','password','email')


class UserProfileInfoForm(forms.ModelForm):
	"""
	Form design for extending the default user model 
	"""
	class Meta():
		model = UserProfileInfo
		fields = ('name','age', 'user_type')

class TeamForm(forms.ModelForm):
	"""
	Form design for creating a team 
	"""
	class Meta():
		model = Teams
		exclude = ()

class TeamMemberForm(forms.ModelForm):
	"""
	Form design for creating a team member
	"""
	class Meta():
		model = TeamMembers
		exclude = ()

class MatchSchedulingForm(forms.ModelForm):
	"""
	Form design for scheduling matches
	"""
	class Meta():
		model = MatchScheduling
		exclude = ()

tournament/footBallApp/views.py
from django.shortcuts import render
from footBallApp.forms import UserForm,UserProfileInfoForm, TeamForm, TeamMemberForm, MatchSchedulingForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from .models import *

def index(request):
    """
    Home page view
    """
    teams_obj = Teams.objects.all()
    Full_list = []
    teams_list = []
    for teams in teams_obj:
        team_dict = {}
        team_dict.update({'team':teams.team_name, 'coach':teams.coach, 'manager':teams.manager})
        team_member_obj = TeamMembers.objects.filter(team=teams)
        for each in team_member_obj:
            data = {}
            data.update({'name':each, 'age':each.age, 'position':each.position})
            teams_list.append(data)
        team_dict.update({'members':teams_list})
        teams_list = []
        Full_list.append(team_dict)
    return render(request,'footBallApp/index.html',{'team':Full_list})
    
@login_required
def special(request):
    """
    Method to obtain the response
    """
    return HttpResponse("You are logged in !")

@login_required
def user_logout(request):
    """
    Logout method
    """
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
    """
    To create a superuser such as Admin, Manager. They have the provision to view
    and add teams, teamplayers, assigning match schedules.
    """
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()
            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    return render(request,'footBallApp/registration.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})
def user_login(request):
    """
    Login function in which the admin or the manager can login to the platform
    """
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request,user)
                # return HttpResponseRedirect(reverse('index'))
                user_form = UserForm()
                profile_form = UserProfileInfoForm()
                teams_obj = Teams.objects.all()
                Full_list = []
                teams_list = []
                for teams in teams_obj:
                    team_dict = {}
                    team_dict.update({'team':teams.team_name, 'coach':teams.coach, 'manager':teams.manager})
                    team_member_obj = TeamMembers.objects.filter(team=teams)
                    for each in team_member_obj:
                        data = {}
                        data.update({'name':each, 'age':each.age, 'position':each.position})
                        teams_list.append(data)
                    team_dict.update({'members':teams_list})
                    teams_list = []
                    Full_list.append(team_dict)
                return render(request,'footBallApp/index.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'team':Full_list
                           })
            else:
                return HttpResponse("Your account was inactive.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details given")
    else:
        return render(request, 'footBallApp/login.html', {})

def addTeam(request):
    """
    Add a new team with a coach and manager
    """
    registered = False
    if request.method == 'POST':
        team_form = TeamForm(data=request.POST)
        if team_form.is_valid():
            team = team_form.save()
            registered = True
        else:
            print(team_form.errors)
    else:
        team_form = TeamForm()
    return render(request,'footBallApp/team.html',
                          {'team_form':team_form,
                           'registered':registered})

def addTeamMember(request):
    """
    Add new team members to the previously added teams
    """
    registered = False
    if request.method == 'POST':
        team_member_form = TeamMemberForm(data=request.POST)
        if team_member_form.is_valid():
            team_member = team_member_form.save()
            registered = True
        else:
            print(team_member_form.errors)
    else:
        team_member_form = TeamMemberForm()
    return render(request,'footBallApp/team_member.html',
                          {'team_member_form':team_member_form,
                           'registered':registered})

def matchScheduling(request):
    """
    Assigning match schedules, Adding results when the match once completed
    """ 
    registered = False
    if request.method == 'POST':
        scheduling_form = MatchSchedulingForm(data=request.POST)
        if scheduling_form.is_valid():
            scheduling = scheduling_form.save()
            registered = True
        else:
            print(scheduling_form.errors)
    else:
        scheduling_form = MatchSchedulingForm()
    matches_obj = MatchScheduling.objects.all()
    return render(request,'footBallApp/match_scheduling.html',
                          {'scheduling_form':scheduling_form,
                           'registered':registered, 'matches_obj':matches_obj})

tournament/templates/footBallApp/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
{# Django Home Link / Admin Link / Register Link#}
          <li><a class="navbar-brand" href="{% url 'index' %}">Home</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'footBallApp:register' %}">Register</a></li>     
          {# Some logic on what to display for last item#}
          {% if user.is_authenticated %}
            <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'footBallApp:user_login' %}">Login</a></li>
          {% endif %}
</ul>
      </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>
  </body>
</html>

tournament/templates/footBallApp/index.html
{% extends "footBallApp/base.html" %}
{% block body_block %}
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
.collapsible {
  background-color: #777;
  color: white;
  cursor: pointer;
  padding: 18px;
  width: 100%;
  border: none;
  text-align: left;
  outline: none;
  font-size: 15px;
}

.active, .collapsible:hover {
  background-color: #555;
}

.content {
  padding: 0 18px;
  display: none;
  overflow: hidden;
  background-color: #f1f1f1;
}
</style>
<div class="container">
  <div class="jumbotron">
    <h1>Welcome to the world of FootBall</h1>
    {% if user.is_authenticated %}
        <h3>Login user :  {{ user.username }}</h3>
        <li><a href="{% url 'footBallApp:addTeam' %}">Add team</a></li>
        <li><a href="{% url 'footBallApp:addTeamMember' %}">Add team member</a></li>
        <li><a href="{% url 'footBallApp:matchScheduling' %}">Match Scheduling</a></li>
        <!-- <form enctype="multipart/form-data" method="POST">
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ profile_form.as_p }}
            <input type="submit" name="" value="Register">
          </form> -->
            <p>List of teams</p>
            {% for obj in team %}
            <button type="button" class="collapsible">{{ obj.team }}</button>
            <div class="content">
              {% if obj.members %}
              <p>
              <table class="table table-striped">
                <thead>
                        <tr>
                            <th>Player</th>
                            <th>Age</th>
                            <th>Position</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for each in obj.members %}
                        <tr>
                            <td>{{each.name}}</td>
                            <td>{{each.age}}</td>
                            <td>{{each.position}}</td>
                        </tr>
                    </tbody>
                </table>
                {% empty %} 
                <li>Sorry, no players in this team.</li> 
                        {% endfor %}
            </div></p>
            {% endif %}
            {% endfor %}
    {% else %}
        <h2>Register or Login if you'd like to</h2>
    {% endif %}
  </div>
</div>
<script>
    var coll = document.getElementsByClassName("collapsible");
    var i;
    
    for (i = 0; i < coll.length; i++) {
      coll[i].addEventListener("click", function() {
        this.classList.toggle("active");
        var content = this.nextElementSibling;
        if (content.style.display === "block") {
          content.style.display = "none";
        } else {
          content.style.display = "block";
        }
      });
    }
    </script>
{% endblock %}

tournament/templates/footBallApp/login.html
{% extends 'footBallApp/base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Login here :</h1>
<form method="post" action="{% url 'footBallApp:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">
<label for="password">Password:</label>
          <input type="password" name="password" placeholder="Password">
<input type="submit" name="" value="Login">
</form>
</div>
  </div>
{% endblock %}

tournament/templates/footBallApp/match_scheduling.html
{% extends "footBallApp/base.html" %}
{% load static %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h4>Match scheduling successfully</h4>
      {% else %}
        <h3>Create a match schedule</h3>
        <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ scheduling_form.as_p }}
          <input type="submit" name="" value="Add">
        </form>
        
      {% endif %}
      <center><h3>Match Schedulings</h3></center>
      <table class="table table-striped">
        <thead>
            <tr>
                <th>Team1</th>
                <th>Team2</th>
                <th>Start Time</th>
                <th>End Time</th>
                <th>Match Status</th> 
                <th>Result</th>       
            </tr>
        </thead>
        <tbody>
      {% for match in matches_obj %}
        <tr><td>{{ match.first_team }}</td><td>{{ match.second_team }}</td><td>{{ match.start_time }}</td>
            <td>{{ match.end_time }}</td><td>{{ match.match_status }}</td><td>{{ match.result }}</td></tr>
      {% endfor %}
    </tbody>
    </table>
    </div>
  </div>
{% endblock %}

tournament/templates/footBallApp/registration.html
{% extends "footBallApp/base.html" %}
{% load static %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>
<form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>
        
      {% endif %}
    </div>
  </div>
{% endblock %}

tournament/templates/footBallApp/team.html
{% extends "footBallApp/base.html" %}
{% load static %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h4>Team added successfully!</h4>
      {% else %}
        <h3>Add a team</h3>
        <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ team_form.as_p }}
          <input type="submit" name="" value="Add">
        </form>
        
      {% endif %}
    </div>
  </div>
{% endblock %}

tournament/templates/footBallApp/team_member.html
{% extends "footBallApp/base.html" %}
{% load static %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h4>Team member added successfully!</h4>
      {% else %}
        <h3>Add a team member</h3>
        <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ team_member_form.as_p }}
          <input type="submit" name="" value="Add">
        </form>
        
      {% endif %}
    </div>
  </div>
{% endblock %}